local pixel = lg.newImage("res/img/pixel.png")
local leaf = lg.newImage("res/img/leaf.png")
local line = lg.newImage("res/img/line.png")

local effects = {}

effects.bokeh = lg.newParticleSystem(pixel,1000)
effects.bokeh:setEmissionArea("uniform",screen_width,screen_height)
effects.bokeh:setEmissionRate(50)
effects.bokeh:setEmitterLifetime(-1)
effects.bokeh:setLinearAcceleration(-5,1,5,5)
effects.bokeh:setParticleLifetime(3,5)
effects.bokeh:setOffset(8,8)
effects.bokeh:setSizes(0.5,1,1.5)
effects.bokeh:setSizeVariation(1)
effects.bokeh:setColors(1,1,1,0, 1,1,1,0.5, 1,1,1,0)

effects.levelup = lg.newParticleSystem(pixel,1000)
effects.levelup:setDirection(1.6)
effects.levelup:setEmissionArea("uniform",screen_width,10)
effects.levelup:setParticleLifetime(1,1.5)
effects.levelup:setRadialAcceleration(-11,11)
effects.levelup:setRotation(-15,15)
effects.levelup:setSpeed(-100,10)
effects.levelup:setLinearDamping(1)
effects.levelup:setSizes(1,2,3)
effects.levelup:setSizeVariation(1)
effects.levelup:setColors(230,205,115,127, 230,205,115,255, 255,255,255,0 )

effects.combat_wipe = lg.newParticleSystem(leaf,1000)
effects.combat_wipe:setDirection(-2.75)
effects.combat_wipe:setEmissionArea("uniform", 20, screen_width/1.5)
effects.combat_wipe:setParticleLifetime(0.65,1)
effects.combat_wipe:setRadialAcceleration(-11,11)
effects.combat_wipe:setRotation(-15,15)
effects.combat_wipe:setSpin(0,math.pi)
effects.combat_wipe:setSpeed(-500,-100)
effects.combat_wipe:setLinearDamping(4)
effects.combat_wipe:setSizes(0.5,0.25,1)
effects.combat_wipe:setSizeVariation(1)
effects.combat_wipe:setColors(255,255,255,255, 255,255,255,0)

effects.radial = lg.newParticleSystem(pixel,1000)
effects.radial:setDirection(0)
effects.radial:setSpread(7)
effects.radial:setParticleLifetime(0.25,1)
effects.radial:setRadialAcceleration(0,5)
effects.radial:setRotation(0,180)
effects.radial:setSpeed(450,450)
effects.radial:setLinearDamping(5)
effects.radial:setSizes(2,0.5)
effects.radial:setColors(0.5*255,0.7*255,255,255, 0.5*255,0.7*255,255,0)

effects.item_sparkle = lg.newParticleSystem(pixel,1000)
effects.item_sparkle:setEmissionRate(0)
effects.item_sparkle:setEmitterLifetime(-1)
effects.item_sparkle:setSpread(math.pi*2)
effects.item_sparkle:setRotation(0,180)
effects.item_sparkle:setParticleLifetime(0.25,1.25)
effects.item_sparkle:setRadialAcceleration(5,10)
effects.item_sparkle:setSpeed(75,150)
effects.item_sparkle:setLinearDamping(4)
effects.item_sparkle:setSizes(0.6,0.8,1)
effects.item_sparkle:setColors(1,1,1,1, 1,1,1,0)

effects.victory = lg.newParticleSystem(line,1000)
effects.victory:setEmissionArea("uniform", 2, 2)
effects.victory:setEmissionRate(500)
effects.victory:setEmitterLifetime(-1)
effects.victory:setSpread(math.pi*2)
effects.victory:setRelativeRotation(true)
effects.victory:setParticleLifetime(0.5)
effects.victory:setSpeed(1000)
effects.victory:setSizes(0.8,0.5,1)
effects.victory:setColors(1,1,1,0, 1,1,1,0, 1,1,1,1, 1,1,1,1, 1,1,1,1, 1,1,1,1)

effects.flee_success = lg.newParticleSystem(pixel,250)
effects.flee_success:setSpread(math.pi*2)
effects.flee_success:setRelativeRotation(true)
effects.flee_success:setParticleLifetime(0.8,1)
effects.flee_success:setRadialAcceleration(-30,30)
effects.flee_success:setRotation(-15,15)
effects.flee_success:setSpeed(50,250)
effects.flee_success:setLinearDamping(4)
effects.flee_success:setSizes(1,2)
effects.flee_success:setSizeVariation(1)
effects.flee_success:setColors(1,1,1,1, 1,1,1,0)

return effects