vignette = lg.newImage("res/img/vignette.png")
squarrow = lg.newImage("res/img/squarrow.png")
fadeline = lg.newImage("res/img/fadeline.png")
fadegradient = lg.newImage("res/img/gradient.png")
splotch = lg.newImage("res/img/splotch.png")